llkeywords version 3
; Version 3 is an extension of LL's version 2 format for the Cool VL Viewer:
; the colors of the highlights are no more given as LLColor3 equivalent
; tripplets, such as [word .1, .3, .1]  (although the latter would still be
; understood and usable), but as the name of a color entry in colors_base.xml,
; such as [word LslSectionsTextFgColor]. This allows to change the highlighting
; colors on a per-skin basis.
; Also, the comment character for this file has been changed from '#' to ';' so
; to allow highligthing preprocessor #directives.
; Finally, ':' has been replaced with '|' to trigger a line feed in the tool
; tip, so that ':' can be used for the SLua parameters in the keywords syntax.

; Sections
[word LslSectionsTextFgColor]
default 	Name of default state that all scripts must have
state 		Keyword to indicate state block or state transition

; Flow control keywords
[word LslFlowControlTextFgColor]
for			for loop|for (initializer; test; iteration)|{|   statements|}
do			do loop|do|{|   statements|} while (test);
while		while loop|while (test)|{    statements|}
if			if statement|if (test)|{    statements|}
else		else clause|if (test)|{    statements|}|else|{    statements|}
jump		jump statement|jump label;|
return		Leave current function or event handler

; Flow control label
[line LslFlowControlTextFgColor]
@			Label|Target for jump statement

; Comment
[one_sided_delimiter LslFlowCommentsTextFgColor]
//			Comment|Non-functional commentary or disabled code

; Comment
[two_sided_delimiter LslFlowCommentsTextFgColor]
/*			Multi-line comment|Non-functional commentary or disabled code, ending with */

; Events
[word LslEventsTextFgColor]
state_entry						state_entry()|Triggered on any state transition and startup
state_exit						state_exit()|Triggered on any state transition
touch_start						touch_start(integer num_detected)|Triggered by the start of agent clicking on task
touch							touch(integer num_detected)|Triggered while agent is clicking on task
touch_end						touch_end(integer num_detected)|Triggered when agent stops clicking on task
collision_start					collision_start(integer num_detected)|Triggered when task starts colliding with another task
collision						collision(integer num_detected)|Triggered while task is colliding with another task
collision_end					collision_end(integer num_detected)|Triggered when task stops colliding with another task
land_collision_start			land_collision_start(vector pos)|Triggered when task starts colliding with land
land_collision					land_collision(vector pos)|Triggered when task is colliding with land
land_collision_end				land_collision_end(vector pos)|Triggered when task stops colliding with land
timer							timer()|Result of the llSetTimerEvent library function call.
listen							listen(integer channel, string name, key id, string message)|Result of the llListen library function call
sensor							sensor(integer num_detected)|Result of the llSensor library function call
no_sensor						no_sensor()|Result of the llSensor library function call
control							control(key id, integer level, integer edge)|Result of llTakeControls library function call
at_target						at_target(integer tnum, vector targetpos, vector ourpos)|Result of llTarget library function call
not_at_target					not_at_target()|Result of llTarget library function call
at_rot_target					at_rot_target(integer tnum, rotation targetrot, rotation ourrot)|Result of llRotTarget library function call
not_at_rot_target				not_at_rot_target()|Result of llRotTarget library function call
money							money(key id, integer amount)|Triggered from an llTransferLindenDollars() call.|'id' matches the return value of the llTransferLindenDollars() call and if the transaction was a success will match the 'transaction id' shown in transaction history on secondlife.com.|'success' is TRUE if the transfer succeeded otherwise FALSE.|On successful transaction'data' will contain a CSV of destination ID and amount transferred. In failure cases it will contain an error tag on failure.
transaction_result				transaction_result(key id, integer success, string data)|Triggered when L$ is given to task
email							email(string time, string address, string subj, string message, integer num_left)|Triggered when task receives email
run_time_permissions			run_time_permissions(integer perm)|Triggered when an agent grants run time permissions to task
attach							attach(key id)|Triggered when task attaches or detaches from agent
dataserver						dataserver(key queryid, string data)|Triggered when task receives asynchronous data
moving_start					moving_start()|Triggered when task begins moving
moving_end						moving_end()|Triggered when task stops moving
on_rez							on_rez(integer start_param)|Triggered when task is rezed in from inventory or another task
object_rez						object_rez(key id)|Triggered when task rezes in another task
link_message					link_message(integer sender_num, integer num, string str, key id)|Triggered when task receives a link message via llMessageLinked library function call
changed							changed(integer change)|Triggered various event change the task|(test 'change' with CHANGED_INVENTORY, CHANGED_COLOR, CHANGED_SHAPE, CHANGED_SCALE, CHANGED_TEXTURE, CHANGED_LINK, CHANGED_ALLOWED_DROP, CHANGED_OWNER, CHANGED_REGION, CHANGED_TELEPORT, CHANGED_REGION_START, CHANGED_MEDIA, CHANGED_RENDER_MATERIAL)
remote_data						remote_data(integer event_type, key channel, key message_id, string sender, integer idata, string sdata)|Triggered by various XML-RPC calls (event_type will be one of REMOTE_DATA_CHANNEL, REMOTE_DATA_REQUEST, REMOTE_DATA_REPLY)
http_response					http_response(key request_id, integer status, list metadata, string body)|Triggered when task receives a response to one of its llHTTPRequests
http_request					http_request(key id, string method, string body)|Triggered when task receives an http request against a public URL
path_update						path_update(integer type, list reserved)|Triggered when task receives a path finding event. The event 'type' is passed as an integer (see the PU_* constants). The list parameter is 'reserved' for future use.
experience_permissions			experience_permissions(key agent_id)|Triggered when the agent (whose key is agent_id) has approved an experience permissions request.
experience_permissions_denied	experience_permissions_denied(key agent_id, integer reason)|Triggered when the agent (whose key is agent_id) has denied an experience permission. 'reason' contains the error code (see the XP_ERROR_* constants).
linkset_data					linkset_data(integer action, string name, string value)|Triggered whenever the linkset data storage is changed.
on_damage						on_damage(integer num_detected)|Triggered when damage has been inflicted on an avatar or task in the world but before damage has been applied or distributed.
on_death						on_death()|Triggered on all attachments worn by an avatar when that avatar's health reaches 0.
final_damage					final_damage(integer num_detected)|Triggered after all on_damage events in all scripts and attachments have processed and damage has been applied to the avatar or distributed to all seated avatars.
game_control					game_control(key id, integer button_levels, list axes)|Triggered when compatible viewer (not yet implemented in the Cool VL Viewer), sends fresh GameControlInput message, but only for scripts on attachments or seat.
